### ISSUE TITLE
Suggestion: FastImage support

### ISSUE THREAD

**Issue by turingpavan** [ihor/react-native-scalable-image#15]
Hi @ihor 
Awesome package. Can you please provide fastImage support? Image component doesn't caches images

**Comment by aaveidt** [comment]
@turingpavan have you found the solution yet?

**Comment by khalidahmedshalabi** [comment]
Any updates?

**Comment by emilioheinz** [comment]
+ 1

**Comment by harveyappleton** [comment]
@dzpt @khalidahmedshalabi @emilioheinz @turingpavan hey guys, i just transitioned over to fastimage instead of this library and it works great. You can adjust the resizeMode which will contain/cover in same way as this scalable image library.

Downside is fast-image looks like a bit of an abandoned library, but all still working

Hope that helps

**Comment by dongdyang** [comment]
@harveyappleton what does it mean?
